AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/*
    - vendor/**/*


Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

# sometimes, this cop will conflict with Rails/Blank to create an un-solvable conflict
# prefer .blank? in this project :)
Rails/Present:
  Enabled: false

# mongoid likes to throw errors when using find_by, so prefer .where().first
Rails/FindBy:
  Enabled: false

inherit_from: .rubocop_todo.yml
